# Generated by Django 3.2.5 on 2021-07-12 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=50, verbose_name='Shop title')),
                ('shop_url', models.SlugField(verbose_name='Shop url')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=50, verbose_name='Review title')),
                ('review_text', models.CharField(max_length=255, verbose_name='Review text')),
                ('review_stars', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Stars')),
                ('review_dt', models.DateTimeField(auto_now=True, verbose_name='Review created at')),
                ('review_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops_reviews.shop')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
