# Generated by Django 3.2.5 on 2021-07-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_shop',
        ),
        migrations.AddField(
            model_name='review',
            name='shop_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Shop url'),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
