# Generated by Django 3.2.5 on 2021-07-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops_reviews', '0002_auto_20210712_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='shop_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shop link'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='User'),
        ),
    ]
