# Generated by Django 3.2.5 on 2021-07-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops_reviews', '0003_auto_20210712_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='shop_url',
        ),
    ]
